import { UserProfile, NeedPost } from "./types";

// ─── 30 Diverse Budapest Profiles ─────────────────────────────────

export const SEED_PROFILES: UserProfile[] = [
  {
    id: "prof-1",
    userName: "Anna K.",
    neighborhood: "District VII",
    avatarColor: "#E8927C",
    bio: "Animal lover and part-time dog trainer. I spend most of my free time at the local shelter.",
    offerings: [
      { id: "o-1a", skill: "Dog walking", category: "pet care", availability: "weekdays" },
      { id: "o-1b", skill: "Pet sitting", category: "pet care", availability: "flexible" },
      { id: "o-1c", skill: "Dog training (basics)", category: "pet care" },
      { id: "o-1d", skill: "Cat grooming", category: "pet care" },
      { id: "o-1e", skill: "House sitting", category: "home services", availability: "weekends" },
    ],
    openToNegotiation: true,
    openToCash: false,
    trustScore: 4.2,
    verified: true,
    linkedSocials: ["linkedin"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-2",
    userName: "Bence T.",
    neighborhood: "District V",
    avatarColor: "#7CC0E8",
    bio: "Certified accountant with 10 years of experience. I also do financial coaching on the side.",
    offerings: [
      { id: "o-2a", skill: "Personal tax filing", category: "finance" },
      { id: "o-2b", skill: "Bookkeeping", category: "finance" },
      { id: "o-2c", skill: "Financial planning advice", category: "finance" },
      { id: "o-2d", skill: "VAT returns for small businesses", category: "finance" },
      { id: "o-2e", skill: "Excel / spreadsheet setup", category: "technology" },
      { id: "o-2f", skill: "Budget coaching", category: "finance" },
    ],
    openToNegotiation: false,
    openToCash: true,
    trustScore: 4.8,
    verified: true,
    linkedSocials: ["linkedin", "facebook"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-3",
    userName: "Clara M.",
    neighborhood: "District XIII",
    avatarColor: "#B07CE8",
    bio: "PhD student in physics. I love teaching and making complicated things simple.",
    offerings: [
      { id: "o-3a", skill: "Math tutoring (all levels)", category: "education" },
      { id: "o-3b", skill: "Physics tutoring", category: "education" },
      { id: "o-3c", skill: "University entrance exam prep", category: "education" },
      { id: "o-3d", skill: "Homework help (STEM)", category: "education" },
      { id: "o-3e", skill: "Research assistance", category: "education" },
      { id: "o-3f", skill: "LaTeX document formatting", category: "technology" },
    ],
    openToNegotiation: true,
    openToCash: false,
    trustScore: 4.5,
    verified: false,
    linkedSocials: ["linkedin"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-4",
    userName: "Dávid R.",
    neighborhood: "District XI",
    avatarColor: "#7CE8A3",
    bio: "Handyman by trade, 20 years in construction. There's nothing around the house I can't fix.",
    offerings: [
      { id: "o-4a", skill: "Plumbing repairs", category: "home services" },
      { id: "o-4b", skill: "Interior painting", category: "home services" },
      { id: "o-4c", skill: "Furniture assembly", category: "home services" },
      { id: "o-4d", skill: "Drywall patching", category: "home services" },
      { id: "o-4e", skill: "Electrical (minor)", category: "home services" },
      { id: "o-4f", skill: "Tile work", category: "home services" },
      { id: "o-4g", skill: "Door / lock replacement", category: "home services" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.0,
    verified: true,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-5",
    userName: "Eszter N.",
    neighborhood: "District VII",
    avatarColor: "#E8D07C",
    bio: "Professional cleaner for 8 years. I also bake cakes and pastries for events.",
    offerings: [
      { id: "o-5a", skill: "Deep cleaning (apartments)", category: "home services" },
      { id: "o-5b", skill: "Move-in/move-out cleaning", category: "home services" },
      { id: "o-5c", skill: "Window cleaning", category: "home services" },
      { id: "o-5d", skill: "Custom cake baking", category: "food services" },
      { id: "o-5e", skill: "Pastry catering (events)", category: "food services" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 3.9,
    verified: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-6",
    userName: "Ferenc L.",
    neighborhood: "District IX",
    avatarColor: "#7CE8D8",
    bio: "Full-stack web developer. I build websites, apps, and automations. Also a home barista.",
    offerings: [
      { id: "o-6a", skill: "Website development", category: "technology" },
      { id: "o-6b", skill: "Landing page design", category: "technology" },
      { id: "o-6c", skill: "Bug fixing (web apps)", category: "technology" },
      { id: "o-6d", skill: "SEO setup", category: "technology" },
      { id: "o-6e", skill: "Social media automation", category: "technology" },
      { id: "o-6f", skill: "Coffee brewing workshop", category: "food services" },
    ],
    openToNegotiation: false,
    openToCash: true,
    trustScore: 4.6,
    verified: true,
    linkedSocials: ["linkedin", "github"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-7",
    userName: "Gréta S.",
    neighborhood: "District XIII",
    avatarColor: "#E87CA0",
    bio: "Social worker specialising in elder care. I genuinely enjoy helping people in my community.",
    offerings: [
      { id: "o-7a", skill: "Grocery shopping for elderly", category: "elder care" },
      { id: "o-7b", skill: "Elderly companionship visits", category: "elder care" },
      { id: "o-7c", skill: "Medication reminders / pickup", category: "elder care" },
      { id: "o-7d", skill: "Light housekeeping for seniors", category: "elder care" },
      { id: "o-7e", skill: "Errand running", category: "errands" },
    ],
    openToNegotiation: true,
    openToCash: false,
    trustScore: 4.3,
    verified: true,
    linkedSocials: ["facebook"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-8",
    userName: "Hanna V.",
    neighborhood: "District VI",
    avatarColor: "#C0E87C",
    bio: "Freelance photographer. I do corporate headshots, events, and product photography.",
    offerings: [
      { id: "o-8a", skill: "Professional headshots", category: "creative services" },
      { id: "o-8b", skill: "Event photography", category: "creative services" },
      { id: "o-8c", skill: "Product photography", category: "creative services" },
      { id: "o-8d", skill: "Photo retouching", category: "creative services" },
      { id: "o-8e", skill: "Lightroom presets / editing lessons", category: "education" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.1,
    verified: false,
    linkedSocials: ["instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-9",
    userName: "István B.",
    neighborhood: "District II",
    avatarColor: "#7C8AE8",
    bio: "Retired chef. I cook traditional Hungarian food and run pop-up dinner parties.",
    offerings: [
      { id: "o-9a", skill: "Hungarian home cooking", category: "food services" },
      { id: "o-9b", skill: "Meal prep (weekly)", category: "food services" },
      { id: "o-9c", skill: "Dinner party catering", category: "food services" },
      { id: "o-9d", skill: "Cooking lessons (Hungarian cuisine)", category: "education" },
      { id: "o-9e", skill: "Preserves & pickling", category: "food services" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 3.7,
    verified: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-10",
    userName: "Judit F.",
    neighborhood: "District VIII",
    avatarColor: "#E8A07C",
    bio: "Graphic designer and illustrator. I can make anything look beautiful.",
    offerings: [
      { id: "o-10a", skill: "Logo design", category: "creative services" },
      { id: "o-10b", skill: "Flyer / poster design", category: "creative services" },
      { id: "o-10c", skill: "Social media graphics", category: "creative services" },
      { id: "o-10d", skill: "Brand identity packages", category: "creative services" },
      { id: "o-10e", skill: "Illustration", category: "creative services" },
      { id: "o-10f", skill: "Canva template creation", category: "creative services" },
    ],
    openToNegotiation: false,
    openToCash: true,
    trustScore: 4.4,
    verified: true,
    linkedSocials: ["linkedin", "instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-11",
    userName: "Kristóf P.",
    neighborhood: "District III",
    avatarColor: "#7CE8C0",
    bio: "Music teacher and café owner. I teach guitar, piano, and ukulele. Also have 200+ bottles of wine in my cellar.",
    offerings: [
      { id: "o-11a", skill: "Guitar lessons", category: "education" },
      { id: "o-11b", skill: "Piano lessons", category: "education" },
      { id: "o-11c", skill: "Ukulele lessons", category: "education" },
      { id: "o-11d", skill: "Wine (bulk, Hungarian)", category: "goods", description: "200+ bottles of Egri Bikavér, Tokaji, etc." },
      { id: "o-11e", skill: "Wine tasting event hosting", category: "food services" },
      { id: "o-11f", skill: "Live music for events", category: "creative services" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.7,
    verified: true,
    linkedSocials: ["facebook", "instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-12",
    userName: "Laura H.",
    neighborhood: "District V",
    avatarColor: "#E87CD0",
    bio: "Yoga instructor and wellness coach. I also make handmade candles and soaps.",
    offerings: [
      { id: "o-12a", skill: "Private yoga sessions", category: "fitness" },
      { id: "o-12b", skill: "Group yoga classes", category: "fitness" },
      { id: "o-12c", skill: "Meditation coaching", category: "fitness" },
      { id: "o-12d", skill: "Handmade candles (bulk)", category: "goods", description: "Soy wax, various scents, gift sets available" },
      { id: "o-12e", skill: "Handmade soaps", category: "goods" },
      { id: "o-12f", skill: "Wellness workshop hosting", category: "fitness" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.9,
    verified: true,
    linkedSocials: ["linkedin", "instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-13",
    userName: "Márton G.",
    neighborhood: "District XI",
    avatarColor: "#A0E87C",
    bio: "Bike mechanic and cycling enthusiast. I run a small garage out of my apartment building.",
    offerings: [
      { id: "o-13a", skill: "Bike repair", category: "maintenance" },
      { id: "o-13b", skill: "Bike tune-up", category: "maintenance" },
      { id: "o-13c", skill: "Wheel truing", category: "maintenance" },
      { id: "o-13d", skill: "Bike fitting / sizing", category: "maintenance" },
      { id: "o-13e", skill: "Used bike parts (inventory)", category: "goods", description: "Tires, chains, brake pads, saddles" },
    ],
    openToNegotiation: true,
    openToCash: false,
    trustScore: 4.0,
    verified: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-14",
    userName: "Nóra J.",
    neighborhood: "District IX",
    avatarColor: "#E8E07C",
    bio: "Freelance translator (HU ↔ EN ↔ DE). Also a licensed real estate agent.",
    offerings: [
      { id: "o-14a", skill: "Hungarian → English translation", category: "language services" },
      { id: "o-14b", skill: "Hungarian → German translation", category: "language services" },
      { id: "o-14c", skill: "Document notarisation assistance", category: "legal" },
      { id: "o-14d", skill: "Real estate advice (Budapest)", category: "consulting" },
      { id: "o-14e", skill: "Apartment viewings / tours", category: "consulting" },
      { id: "o-14f", skill: "Hungarian language lessons", category: "education" },
    ],
    openToNegotiation: false,
    openToCash: true,
    trustScore: 4.5,
    verified: true,
    linkedSocials: ["linkedin"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-15",
    userName: "Olivér D.",
    neighborhood: "District VI",
    avatarColor: "#7CBAE8",
    bio: "Former banker turned startup advisor. I have contacts everywhere and 50kg of specialty coffee beans I import from Colombia.",
    offerings: [
      { id: "o-15a", skill: "Personal tax returns", category: "finance" },
      { id: "o-15b", skill: "Startup / business advice", category: "consulting" },
      { id: "o-15c", skill: "Investor pitch coaching", category: "consulting" },
      { id: "o-15d", skill: "Specialty coffee beans (bulk)", category: "goods", description: "Colombian single-origin, 50kg available" },
      { id: "o-15e", skill: "Networking introductions", category: "consulting" },
      { id: "o-15f", skill: "Financial modelling", category: "finance" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.3,
    verified: true,
    linkedSocials: ["linkedin", "twitter"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-16",
    userName: "Petra W.",
    neighborhood: "District XIV",
    avatarColor: "#8CE8A0",
    bio: "Landscape gardener and plant enthusiast. I turn sad balconies into jungles and maintain community gardens.",
    offerings: [
      { id: "o-16a", skill: "Garden maintenance", category: "home services", availability: "weekdays" },
      { id: "o-16b", skill: "Lawn mowing", category: "home services" },
      { id: "o-16c", skill: "Balcony garden setup", category: "home services" },
      { id: "o-16d", skill: "Plant care consultations", category: "consulting" },
      { id: "o-16e", skill: "Composting advice", category: "consulting" },
    ],
    openToNegotiation: true,
    openToCash: false,
    trustScore: 4.1,
    verified: true,
    linkedSocials: ["instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-17",
    userName: "Róbert K.",
    neighborhood: "District XII",
    avatarColor: "#E87C7C",
    bio: "Auto mechanic for 15 years. I specialise in European cars and do house calls with my mobile toolkit.",
    offerings: [
      { id: "o-17a", skill: "Car diagnostics", category: "automotive" },
      { id: "o-17b", skill: "Oil change", category: "automotive" },
      { id: "o-17c", skill: "Brake repair", category: "automotive" },
      { id: "o-17d", skill: "Tire change / rotation", category: "automotive" },
      { id: "o-17e", skill: "Car detailing", category: "automotive" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.4,
    verified: true,
    linkedSocials: ["facebook"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-18",
    userName: "Sára A.",
    neighborhood: "District III",
    avatarColor: "#D8E87C",
    bio: "Certified nutritionist and sports dietitian. I help people build sustainable eating habits.",
    offerings: [
      { id: "o-18a", skill: "Meal planning", category: "health" },
      { id: "o-18b", skill: "Diet consultation", category: "health" },
      { id: "o-18c", skill: "Sports nutrition advice", category: "health" },
      { id: "o-18d", skill: "Allergy-friendly recipe design", category: "health" },
      { id: "o-18e", skill: "Smoothie / juice workshop", category: "food services" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.6,
    verified: true,
    linkedSocials: ["linkedin", "instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-19",
    userName: "Tamás Z.",
    neighborhood: "District VIII",
    avatarColor: "#7C7CE8",
    bio: "Licensed electrician by day, DJ by night. I wire homes and light up dance floors.",
    offerings: [
      { id: "o-19a", skill: "Electrical installation", category: "home services" },
      { id: "o-19b", skill: "Smart home setup", category: "technology" },
      { id: "o-19c", skill: "DJ for events", category: "creative services" },
      { id: "o-19d", skill: "Sound system rental", category: "goods", description: "PA speakers, mixer, mics for up to 200 people" },
      { id: "o-19e", skill: "Lighting setup (events)", category: "creative services" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 3.8,
    verified: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-20",
    userName: "Virág E.",
    neighborhood: "District II",
    avatarColor: "#E8C87C",
    bio: "Interior designer with an eye for colour. I transform small apartments into cosy, functional spaces.",
    offerings: [
      { id: "o-20a", skill: "Room redesign consultation", category: "creative services" },
      { id: "o-20b", skill: "Colour consultation", category: "creative services" },
      { id: "o-20c", skill: "Furniture sourcing", category: "consulting" },
      { id: "o-20d", skill: "Home staging (for sale)", category: "creative services" },
      { id: "o-20e", skill: "Mood board creation", category: "creative services" },
    ],
    openToNegotiation: false,
    openToCash: true,
    trustScore: 4.7,
    verified: true,
    linkedSocials: ["linkedin", "instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-21",
    userName: "Zoltán M.",
    neighborhood: "District XIV",
    avatarColor: "#7CE8E8",
    bio: "Certified personal trainer and former semi-pro runner. I help people get moving and stay consistent.",
    offerings: [
      { id: "o-21a", skill: "Personal training", category: "fitness" },
      { id: "o-21b", skill: "Running coaching", category: "fitness" },
      { id: "o-21c", skill: "Strength training programs", category: "fitness" },
      { id: "o-21d", skill: "Sports massage", category: "fitness" },
      { id: "o-21e", skill: "Nutrition tips (fitness)", category: "health" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.2,
    verified: true,
    linkedSocials: ["instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-22",
    userName: "Adrienn C.",
    neighborhood: "District VI",
    avatarColor: "#E87CE8",
    bio: "Civil lawyer with a passion for tenant rights. I offer affordable consultations for everyday legal issues.",
    offerings: [
      { id: "o-22a", skill: "Contract review", category: "legal" },
      { id: "o-22b", skill: "Tenant rights advice", category: "legal" },
      { id: "o-22c", skill: "Small claims help", category: "legal" },
      { id: "o-22d", skill: "Legal document drafting", category: "legal" },
      { id: "o-22e", skill: "Mediation services", category: "legal" },
    ],
    openToNegotiation: false,
    openToCash: true,
    trustScore: 4.8,
    verified: true,
    linkedSocials: ["linkedin"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-23",
    userName: "Balázs O.",
    neighborhood: "District IX",
    avatarColor: "#C8A07C",
    bio: "Third-generation carpenter. I build custom furniture, shelving, and anything from wood.",
    offerings: [
      { id: "o-23a", skill: "Custom shelving", category: "home services" },
      { id: "o-23b", skill: "Wooden furniture (custom)", category: "home services" },
      { id: "o-23c", skill: "Cabinet repair", category: "home services" },
      { id: "o-23d", skill: "Deck / terrace building", category: "home services" },
      { id: "o-23e", skill: "Wood finishing & staining", category: "home services" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.3,
    verified: false,
    linkedSocials: ["facebook"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-24",
    userName: "Csilla T.",
    neighborhood: "District V",
    avatarColor: "#E8A8C0",
    bio: "Event planner for 12 years. From birthday parties to corporate galas — I organise it all.",
    offerings: [
      { id: "o-24a", skill: "Birthday party planning", category: "event services" },
      { id: "o-24b", skill: "Corporate event coordination", category: "event services" },
      { id: "o-24c", skill: "Venue sourcing", category: "event services" },
      { id: "o-24d", skill: "Decoration setup", category: "event services" },
      { id: "o-24e", skill: "Catering coordination", category: "event services" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.5,
    verified: true,
    linkedSocials: ["linkedin", "facebook"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-25",
    userName: "Dénes I.",
    neighborhood: "District XI",
    avatarColor: "#7CA8E8",
    bio: "IT support specialist. I fix computers, set up networks, and rescue data from dying hard drives.",
    offerings: [
      { id: "o-25a", skill: "Computer repair", category: "technology" },
      { id: "o-25b", skill: "Virus removal", category: "technology" },
      { id: "o-25c", skill: "Data recovery", category: "technology" },
      { id: "o-25d", skill: "Home network setup", category: "technology" },
      { id: "o-25e", skill: "Printer setup & troubleshooting", category: "technology" },
    ],
    openToNegotiation: true,
    openToCash: false,
    trustScore: 4.0,
    verified: false,
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-26",
    userName: "Emőke R.",
    neighborhood: "District VII",
    avatarColor: "#E8D8A0",
    bio: "Seamstress and tailor for 20 years. I alter, mend, and create — from curtains to wedding dresses.",
    offerings: [
      { id: "o-26a", skill: "Clothing alterations", category: "tailoring" },
      { id: "o-26b", skill: "Custom dress making", category: "tailoring" },
      { id: "o-26c", skill: "Curtain sewing", category: "tailoring" },
      { id: "o-26d", skill: "Upholstery repair", category: "home services" },
      { id: "o-26e", skill: "Embroidery", category: "tailoring" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.6,
    verified: true,
    linkedSocials: ["facebook", "instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-27",
    userName: "Gábor N.",
    neighborhood: "District III",
    avatarColor: "#7CE8B8",
    bio: "Master plumber with 25 years experience. Boilers, pipes, bathrooms — I've done it all.",
    offerings: [
      { id: "o-27a", skill: "Boiler installation", category: "home services" },
      { id: "o-27b", skill: "Pipe fitting", category: "home services" },
      { id: "o-27c", skill: "Drain cleaning", category: "home services" },
      { id: "o-27d", skill: "Bathroom renovation", category: "home services" },
      { id: "o-27e", skill: "Water heater repair", category: "home services" },
    ],
    openToNegotiation: false,
    openToCash: true,
    trustScore: 4.9,
    verified: true,
    linkedSocials: ["facebook"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-28",
    userName: "Hajnalka F.",
    neighborhood: "District XIII",
    avatarColor: "#E8B87C",
    bio: "Professional dog groomer and part-time vet assistant. I adore animals of all shapes and sizes.",
    offerings: [
      { id: "o-28a", skill: "Dog grooming", category: "pet care" },
      { id: "o-28b", skill: "Nail trimming (pets)", category: "pet care" },
      { id: "o-28c", skill: "Pet first aid", category: "pet care" },
      { id: "o-28d", skill: "Puppy socialisation classes", category: "pet care" },
      { id: "o-28e", skill: "Pet photography", category: "creative services" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.3,
    verified: true,
    linkedSocials: ["instagram"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-29",
    userName: "Iván L.",
    neighborhood: "District XII",
    avatarColor: "#E8E8A0",
    bio: "Hobbyist beekeeper with 40 hives in the Buda hills. I sell honey, beeswax, and teach workshops.",
    offerings: [
      { id: "o-29a", skill: "Honey (bulk)", category: "goods", description: "Acacia, wildflower, linden — 100+ jars available" },
      { id: "o-29b", skill: "Beeswax candles", category: "goods" },
      { id: "o-29c", skill: "Beekeeping workshops", category: "education" },
      { id: "o-29d", skill: "Pollination services", category: "home services" },
      { id: "o-29e", skill: "Garden bee consulting", category: "consulting" },
    ],
    openToNegotiation: true,
    openToCash: true,
    trustScore: 4.1,
    verified: false,
    linkedSocials: ["facebook"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "prof-30",
    userName: "Kata S.",
    neighborhood: "District VIII",
    avatarColor: "#A07CE8",
    bio: "Life coach and professional organiser. I help people declutter their homes and their minds.",
    offerings: [
      { id: "o-30a", skill: "Life coaching sessions", category: "consulting" },
      { id: "o-30b", skill: "Moving assistance", category: "home services" },
      { id: "o-30c", skill: "Decluttering service", category: "home services" },
      { id: "o-30d", skill: "Home organising", category: "home services" },
      { id: "o-30e", skill: "Motivational speaking", category: "consulting" },
    ],
    openToNegotiation: true,
    openToCash: false,
    trustScore: 3.9,
    verified: false,
    linkedSocials: ["linkedin", "instagram"],
    createdAt: new Date().toISOString(),
  },
];

// ─── Sample Need Posts ────────────────────────────────────────────
//
// RING DESIGN — these needs + profile offerings form guaranteed cycles:
//
// 2-WAY #1: Anna(prof-1) offers "Dog walking" → Bence needs it
//           Bence(prof-2) offers "Personal tax filing" → Anna needs it
//
// 3-WAY #1: Eszter(prof-5) offers "Deep cleaning" → Clara needs it
//           Clara(prof-3) offers "Math tutoring" → Dávid needs it
//           Dávid(prof-4) offers "Furniture assembly" → Eszter needs a website... no,
//             → Gréta needs it, and Gréta offers elder care → but let's keep it clean:
//           Dávid(prof-4) offers "Plumbing repairs" → Eszter needs plumbing (new need)
//             ... actually let's be explicit:
//
// 3-WAY #1: Clara(prof-3) offers "Math tutoring" → Dávid(prof-4) needs "math tutoring"
//           Dávid(prof-4) offers "Furniture assembly" → Gréta(prof-7) needs "furniture assembly"
//           Gréta(prof-7) offers "Errand running" → Clara(prof-3) needs "errand running"
//
// 3-WAY #2: Hanna(prof-8) offers "Professional headshots" → István(prof-9) needs "headshots"
//           István(prof-9) offers "Hungarian home cooking" → Judit(prof-10) needs "home cooking"
//           Judit(prof-10) offers "Logo design" → Hanna(prof-8) needs "logo design"
//
// 4-WAY #1: Kristóf(prof-11) offers "Guitar lessons" → Laura(prof-12) needs "guitar lessons"
//           Laura(prof-12) offers "Group yoga classes" → Márton(prof-13) needs "yoga"
//           Márton(prof-13) offers "Bike repair" → Nóra(prof-14) needs "bike repair"
//           Nóra(prof-14) offers "Hungarian → English translation" → Kristóf(prof-11) needs "translation"
//
// 3-WAY #3: Eszter(prof-5) offers "Deep cleaning" → Clara(prof-3) needs "deep cleaning"
//           Clara(prof-3) offers "Physics tutoring" → Ferenc(prof-6) needs "physics tutoring"
//           Ferenc(prof-6) offers "Website development" → Eszter(prof-5) needs "website"
//
// 2-WAY #2: Petra(prof-16) offers "Garden maintenance" → Róbert(prof-17) needs it
//           Róbert(prof-17) offers "Car diagnostics" → Petra(prof-16) needs it
//
// 3-WAY #4: Sára(prof-18) offers "Meal planning" → Tamás(prof-19) needs it
//           Tamás(prof-19) offers "Smart home setup" → Virág(prof-20) needs it
//           Virág(prof-20) offers "Room redesign consultation" → Sára(prof-18) needs it
//
// 3-WAY #5: Zoltán(prof-21) offers "Personal training" → Adrienn(prof-22) needs it
//           Adrienn(prof-22) offers "Contract review" → Balázs(prof-23) needs it
//           Balázs(prof-23) offers "Custom shelving" → Zoltán(prof-21) needs it
//
// 4-WAY #2: Csilla(prof-24) offers "Birthday party planning" → Dénes(prof-25) needs it
//           Dénes(prof-25) offers "Computer repair" → Emőke(prof-26) needs it
//           Emőke(prof-26) offers "Clothing alterations" → Gábor(prof-27) needs it
//           Gábor(prof-27) offers "Drain cleaning" → Csilla(prof-24) needs it
//
// 3-WAY #6: Hajnalka(prof-28) offers "Dog grooming" → Iván(prof-29) needs it
//           Iván(prof-29) offers "Honey (bulk)" → Kata(prof-30) needs it
//           Kata(prof-30) offers "Moving assistance" → Hajnalka(prof-28) needs it
//

export const SEED_NEEDS: NeedPost[] = [
  // Anna needs tax filing → Bence offers it (2-way ring #1)
  {
    id: "need-1",
    profileId: "prof-1",
    rawNeed: "I need help with my personal tax filing this month — it's due soon and I'm lost",
    parsedNeeds: [{ skill: "personal tax filing", category: "finance" }],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Bence needs dog walking → Anna offers it (2-way ring #1)
  {
    id: "need-2",
    profileId: "prof-2",
    rawNeed: "I need someone to walk my dog 3 times a week — I travel for work",
    parsedNeeds: [{ skill: "dog walking", category: "pet care" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Clara needs deep cleaning → Eszter offers it (3-way ring #3) + errand running → Gréta offers (3-way #1)
  {
    id: "need-3",
    profileId: "prof-3",
    rawNeed: "I need my apartment deep-cleaned before my parents visit, and someone to run some errands for me",
    parsedNeeds: [
      { skill: "deep cleaning", category: "home services" },
      { skill: "errand running", category: "errands" },
    ],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Dávid needs math tutoring → Clara offers it (3-way ring #1)
  {
    id: "need-4",
    profileId: "prof-4",
    rawNeed: "I need math tutoring for my daughter's university entrance exam",
    parsedNeeds: [{ skill: "math tutoring", category: "education" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Eszter needs website development → Ferenc offers it (3-way ring #3)
  {
    id: "need-5",
    profileId: "prof-5",
    rawNeed: "I need a website built for my small bakery — just a landing page with menu and ordering info",
    parsedNeeds: [{ skill: "website development", category: "technology" }],
    urgency: "low",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Ferenc needs physics tutoring → Clara offers it (3-way ring #3) + elder care → Gréta offers
  {
    id: "need-6",
    profileId: "prof-6",
    rawNeed: "I need a physics tutor for my son, and someone to help my elderly mother with grocery shopping",
    parsedNeeds: [
      { skill: "physics tutoring", category: "education" },
      { skill: "grocery shopping for elderly", category: "elder care" },
    ],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Gréta needs furniture assembly → Dávid offers it (3-way ring #1)
  {
    id: "need-7",
    profileId: "prof-7",
    rawNeed: "I need furniture assembled — just bought a new IKEA wardrobe and desk",
    parsedNeeds: [{ skill: "furniture assembly", category: "home services" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Hanna needs logo design → Judit offers it (3-way ring #2)
  {
    id: "need-8",
    profileId: "prof-8",
    rawNeed: "I need a logo designed for my photography business and some interior painting done",
    parsedNeeds: [
      { skill: "logo design", category: "creative services" },
      { skill: "interior painting", category: "home services" },
    ],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // István needs professional headshots → Hanna offers them (3-way ring #2)
  {
    id: "need-9",
    profileId: "prof-9",
    rawNeed: "I need professional headshots for my LinkedIn profile and new cookbook cover",
    parsedNeeds: [{ skill: "professional headshots", category: "creative services" }],
    urgency: "low",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Judit needs home cooking → István offers it (3-way ring #2)
  {
    id: "need-10",
    profileId: "prof-10",
    rawNeed: "I need someone to cook healthy meals for my family this week — I'm recovering from surgery",
    parsedNeeds: [{ skill: "Hungarian home cooking", category: "food services" }],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Kristóf needs translation → Nóra offers it (4-way ring #1)
  {
    id: "need-11",
    profileId: "prof-11",
    rawNeed: "I need a Hungarian-to-English translator for my café menu and business documents",
    parsedNeeds: [{ skill: "Hungarian → English translation", category: "language services" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Laura needs guitar lessons → Kristóf offers them (4-way ring #1)
  {
    id: "need-12",
    profileId: "prof-12",
    rawNeed: "I want to learn guitar — always wanted to play but never got started",
    parsedNeeds: [{ skill: "guitar lessons", category: "education" }],
    urgency: "low",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Márton needs yoga → Laura offers it (4-way ring #1)
  {
    id: "need-13",
    profileId: "prof-13",
    rawNeed: "I need a yoga instructor for my office team — weekly group sessions for 6 people",
    parsedNeeds: [{ skill: "group yoga classes", category: "fitness" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Nóra needs bike repair → Márton offers it (4-way ring #1)
  {
    id: "need-14",
    profileId: "prof-14",
    rawNeed: "I need my bike fixed — flat tire and the gears are slipping badly",
    parsedNeeds: [{ skill: "bike repair", category: "maintenance" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Olivér needs networking / startup advice — links into other rings as alternate
  {
    id: "need-15",
    profileId: "prof-15",
    rawNeed: "I need bookkeeping help and a coffee brewing workshop for my team",
    parsedNeeds: [
      { skill: "bookkeeping", category: "finance" },
      { skill: "coffee brewing workshop", category: "food services" },
    ],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Petra needs car diagnostics → Róbert offers it (2-way ring #2)
  {
    id: "need-16",
    profileId: "prof-16",
    rawNeed: "My car is making a weird noise when I turn — I need someone to diagnose it before it gets worse",
    parsedNeeds: [{ skill: "car diagnostics", category: "automotive" }],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Róbert needs garden maintenance → Petra offers it (2-way ring #2)
  {
    id: "need-17",
    profileId: "prof-17",
    rawNeed: "I need someone to maintain my garden — it's gotten completely overgrown while I was busy with work",
    parsedNeeds: [{ skill: "garden maintenance", category: "home services" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Sára needs room redesign → Virág offers it (3-way ring #4)
  {
    id: "need-18",
    profileId: "prof-18",
    rawNeed: "I just moved into a new flat and need help redesigning the living room — I have no sense of layout",
    parsedNeeds: [{ skill: "room redesign consultation", category: "creative services" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Tamás needs meal planning → Sára offers it (3-way ring #4)
  {
    id: "need-19",
    profileId: "prof-19",
    rawNeed: "I need a proper meal plan — I'm always eating junk between gigs and my energy is crashing",
    parsedNeeds: [{ skill: "meal planning", category: "health" }],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Virág needs smart home setup → Tamás offers it (3-way ring #4)
  {
    id: "need-20",
    profileId: "prof-20",
    rawNeed: "I want to set up smart lighting and a thermostat in my apartment — I have no idea where to start",
    parsedNeeds: [{ skill: "smart home setup", category: "technology" }],
    urgency: "low",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Zoltán needs custom shelving → Balázs offers it (3-way ring #5)
  {
    id: "need-21",
    profileId: "prof-21",
    rawNeed: "I need custom shelving built in my home gym for equipment storage — nothing off the shelf fits",
    parsedNeeds: [{ skill: "custom shelving", category: "home services" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Adrienn needs personal training → Zoltán offers it (3-way ring #5)
  {
    id: "need-22",
    profileId: "prof-22",
    rawNeed: "I need a personal trainer — I sit at a desk all day and my back is killing me",
    parsedNeeds: [{ skill: "personal training", category: "fitness" }],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Balázs needs contract review → Adrienn offers it (3-way ring #5)
  {
    id: "need-23",
    profileId: "prof-23",
    rawNeed: "I need a lawyer to review a contract for a big furniture order — want to make sure I'm protected",
    parsedNeeds: [{ skill: "contract review", category: "legal" }],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Csilla needs drain cleaning → Gábor offers it (4-way ring #2)
  {
    id: "need-24",
    profileId: "prof-24",
    rawNeed: "The kitchen drain in my office is completely blocked — I need a plumber urgently before our next event",
    parsedNeeds: [{ skill: "drain cleaning", category: "home services" }],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Dénes needs birthday party planning → Csilla offers it (4-way ring #2)
  {
    id: "need-25",
    profileId: "prof-25",
    rawNeed: "I want to throw a surprise birthday party for my wife — I'm hopeless at organising events",
    parsedNeeds: [{ skill: "birthday party planning", category: "event services" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Emőke needs computer repair → Dénes offers it (4-way ring #2)
  {
    id: "need-26",
    profileId: "prof-26",
    rawNeed: "My sewing machine's computer module is acting up and my laptop won't boot — I need tech help badly",
    parsedNeeds: [{ skill: "computer repair", category: "technology" }],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Gábor needs clothing alterations → Emőke offers it (4-way ring #2)
  {
    id: "need-27",
    profileId: "prof-27",
    rawNeed: "I need my work trousers altered — lost weight and nothing fits anymore, also need curtains hemmed",
    parsedNeeds: [
      { skill: "clothing alterations", category: "tailoring" },
      { skill: "curtain sewing", category: "tailoring" },
    ],
    urgency: "low",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Hajnalka needs moving assistance → Kata offers it (3-way ring #6)
  {
    id: "need-28",
    profileId: "prof-28",
    rawNeed: "I'm moving my grooming salon to a new location and need help packing and carrying everything",
    parsedNeeds: [{ skill: "moving assistance", category: "home services" }],
    urgency: "high",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Iván needs dog grooming → Hajnalka offers it (3-way ring #6)
  {
    id: "need-29",
    profileId: "prof-29",
    rawNeed: "My two golden retrievers desperately need grooming — they look like woolly mammoths",
    parsedNeeds: [{ skill: "dog grooming", category: "pet care" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
  // Kata needs honey → Iván offers it (3-way ring #6)
  {
    id: "need-30",
    profileId: "prof-30",
    rawNeed: "I need bulk honey for my wellness retreat gift bags — at least 50 jars of local Hungarian honey",
    parsedNeeds: [{ skill: "honey (bulk)", category: "goods" }],
    urgency: "medium",
    status: "open",
    createdAt: new Date().toISOString(),
  },
];
